"""
================================================================================
 AI-IDS — Setup Wizard & Operations Console
================================================================================

First-time setup wizard plus full operations CLI for end users who have
downloaded the project and want to configure and run it.

Entry points:
    python cli.py                → auto-detect first-run, launch wizard or menu
    python cli.py setup          → force setup wizard
    python cli.py launch         → launch Streamlit UI directly

All other subcommands preserved for CI/automation pipelines.
"""

from __future__ import annotations

import argparse
import io
import json
import platform
import secrets
import subprocess
import sys
import time
from pathlib import Path
from typing import TYPE_CHECKING, Final

from config.settings import DEFAULT_ENV_VARS, INSECURE_SECRET_KEY

if TYPE_CHECKING:
    from services.container import Container


# ---------------------------------------------------------------------------
# Encoding bootstrap — Windows cp1252 → UTF-8
# ---------------------------------------------------------------------------

def _ensure_utf8() -> None:
    if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
        sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

_ensure_utf8()


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_APP_VERSION: Final[str] = "2.0.0"
_BASE_DIR: Final[Path] = Path(__file__).resolve().parent
_ENV_PATH: Final[Path] = _BASE_DIR / ".env"

_DIV: Final[str] = "=" * 62
_SUB: Final[str] = "-" * 62

# Setup wizard / launch defaults (single source of truth lives in
# ``config.settings.DEFAULT_ENV_VARS``; ``cli.py`` must not re-declare them).
_PIP_INSTALL_TIMEOUT_SECONDS: Final[int] = 300
_STREAMLIT_URL: Final[str] = "http://localhost:8501"
_DEFAULT_SOURCE_IP: Final[str] = "127.0.0.1"
_DEFAULT_DEST_IP: Final[str] = "10.0.0.1"
_DEFAULT_ALERT_LIMIT: Final[int] = 10
_DEFAULT_LOG_LIMIT: Final[int] = 20
_SETUP_STEPS: Final[int] = 7


# ===========================================================================
# Helper utilities
# ===========================================================================

def _heading(title: str) -> None:
    print(f"\n{_DIV}")
    print(f"  {title}")
    print(_DIV)


def _subheading(title: str) -> None:
    print(f"\n  {title}")
    print(f"  {_SUB}")


def _prompt(message: str, default: str = "") -> str:
    hint = f" [{default}]" if default else ""
    value = input(f"  {message}{hint}: ").strip()
    return value if value else default


def _confirm(message: str, default: bool = True) -> bool:
    hint = "Y/n" if default else "y/N"
    value = input(f"  {message} [{hint}]: ").strip().lower()
    if not value:
        return default
    return value in ("y", "yes")


def _env_exists() -> bool:
    return _ENV_PATH.exists()


def _detect_os() -> str:
    name = platform.system()
    if name == "Windows":
        return "Windows"
    elif name == "Linux":
        return "Linux"
    elif name == "Darwin":
        return "macOS"
    return name


def _detect_python() -> str:
    return platform.python_version()


def _read_env() -> dict[str, str]:
    result: dict[str, str] = {}
    if not _ENV_PATH.exists():
        return result
    for line in _ENV_PATH.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            result[key] = value
    return result


def _write_env(values: dict[str, str]) -> None:
    lines = [
        "# ==============================================================================",
        "# AI-IDS — Generated Environment Configuration",
        f"# Generated by Setup Wizard v{_APP_VERSION}",
        "# WARNING: Do not commit this file to version control.",
        "# ==============================================================================",
        "",
    ]

    sections = [
        ("# --- Environment & Debug ---", [
            "AI_IDS_ENV", "AI_IDS_DEBUG", "AI_IDS_SECRET_KEY",
        ]),
        ("# --- Paths ---", [
            "AI_IDS_DB_PATH", "AI_IDS_MODELS_DIR", "AI_IDS_LOGS_DIR",
            "AI_IDS_CAPTURED_FLOWS_DIR",
        ]),
        ("# --- Logging ---", [
            "AI_IDS_LOG_LEVEL", "AI_IDS_LOG_TO_CONSOLE",
            "AI_IDS_LOG_MAX_BYTES", "AI_IDS_LOG_BACKUP_COUNT",
        ]),
        ("# --- Security ---", [
            "AI_IDS_BCRYPT_ROUNDS",
        ]),
        ("# --- Alert Engine ---", [
            "AI_IDS_ALERT_WINDOW_MINUTES",
        ]),
        ("# --- Network Capture ---", [
            "AI_IDS_FLOW_IDLE_TIMEOUT", "AI_IDS_MONITORING_INTERVAL",
            "AI_IDS_CICFLOWMETER_INTERVAL_SECONDS",
            "AI_IDS_LIVE_CAPTURE_MODE", "AI_IDS_FLOW_EXTRACTOR",
        ]),
        ("# --- Telegram Notifications ---", [
            "AI_IDS_TELEGRAM_BOT_TOKEN", "AI_IDS_TELEGRAM_CHAT_ID",
        ]),
    ]

    for section_comment, keys in sections:
        lines.append(section_comment)
        for key in keys:
            val = values.get(key, DEFAULT_ENV_VARS.get(key, ""))
            if key in ("AI_IDS_TELEGRAM_BOT_TOKEN", "AI_IDS_TELEGRAM_CHAT_ID", "AI_IDS_SECRET_KEY"):
                if val:
                    lines.append(f'{key}="{val}"')
                else:
                    lines.append(f'{key}=""')
            else:
                lines.append(f"{key}={val}")
        lines.append("")

    _ENV_PATH.write_text("\n".join(lines), encoding="utf-8")


def _get_executable() -> str:
    return sys.executable


def _ensure_config_dirs(values: dict[str, str]) -> None:
    """
    Creates the operational directories referenced by the wizard's configured
    path values. Relative paths are anchored to the project root.
    """
    for key, is_file in (
        ("AI_IDS_DB_PATH", True),
        ("AI_IDS_MODELS_DIR", False),
        ("AI_IDS_LOGS_DIR", False),
        ("AI_IDS_CAPTURED_FLOWS_DIR", False),
    ):
        target = Path(values.get(key, DEFAULT_ENV_VARS.get(key, "")))
        if not target.is_absolute():
            target = _BASE_DIR / target
        (target.parent if is_file else target).mkdir(parents=True, exist_ok=True)


# ===========================================================================
# SETUP WIZARD
# ===========================================================================

def run_setup_wizard() -> bool:
    """Interactive setup wizard. Returns True if completed successfully."""

    _heading("AI-IDS Setup Wizard")
    print("  This wizard will guide you through the initial configuration.")
    print("  Press Enter to accept the default value shown in [brackets].\n")

    values: dict[str, str] = dict(DEFAULT_ENV_VARS)

    # Load existing .env if present
    if _env_exists():
        existing = _read_env()
        values.update(existing)
        print("  Existing .env configuration detected. Defaults updated.\n")

    # ── Step 1: Operating System ──────────────────────────────────────
    _subheading(f"Step 1/{_SETUP_STEPS}: Operating System Detection")
    os_name = _detect_os()
    print(f"  Detected OS : {os_name}")
    print(f"  Python      : {_detect_python()}")
    print(f"  Architecture: {platform.machine()}")
    if not _confirm("  Is this correct?"):
        print("  Please ensure you are running the correct Python version for your OS.")
        return False

    # ── Step 2: Install Dependencies ──────────────────────────────────
    _subheading(f"Step 2/{_SETUP_STEPS}: Install Dependencies")
    req_path = _BASE_DIR / "requirements.txt"
    if not req_path.exists():
        print("  WARNING: requirements.txt not found. Skipping dependency installation.")
    else:
        if _confirm("  Install Python packages from requirements.txt?", default=True):
            print("  Running: pip install -r requirements.txt ...")
            python = _get_executable()
            try:
                result = subprocess.run(
                    [python, "-m", "pip", "install", "-r", str(req_path), "--quiet"],
                    capture_output=True, text=True, timeout=_PIP_INSTALL_TIMEOUT_SECONDS,
                )
                if result.returncode == 0:
                    print("  Dependencies installed successfully.")
                else:
                    print(f"  WARNING: pip returned exit code {result.returncode}")
                    if result.stderr:
                        for line in result.stderr.strip().splitlines()[-5:]:
                            print(f"    {line}")
                    if not _confirm("  Continue anyway?", default=True):
                        return False
            except subprocess.TimeoutExpired:
                print(
                    "  WARNING: pip install timed out "
                    f"({_PIP_INSTALL_TIMEOUT_SECONDS // 60} min limit). Continuing..."
                )
            except FileNotFoundError:
                print("  ERROR: pip not found. Please install dependencies manually.")
                if not _confirm("  Continue anyway?", default=False):
                    return False

    # ── Step 3: Paths ─────────────────────────────────────────────────
    _subheading(f"Step 3/{_SETUP_STEPS}: Directory Paths")
    values["AI_IDS_DB_PATH"] = _prompt("Database file path", values["AI_IDS_DB_PATH"])
    values["AI_IDS_MODELS_DIR"] = _prompt("Models directory", values["AI_IDS_MODELS_DIR"])
    values["AI_IDS_LOGS_DIR"] = _prompt("Logs directory", values["AI_IDS_LOGS_DIR"])
    values["AI_IDS_CAPTURED_FLOWS_DIR"] = _prompt(
        "Captured flows directory", values["AI_IDS_CAPTURED_FLOWS_DIR"]
    )

    # Ensure the configured directories exist (anchored to project root)
    _ensure_config_dirs(values)
    print("  Directories verified/created.")

    # ── Step 4: Security ──────────────────────────────────────────────
    _subheading(f"Step 4/{_SETUP_STEPS}: Security Settings")
    env_choice = _prompt(
        "Environment (1=Development, 2=Production)",
        "1" if values["AI_IDS_ENV"] == "development" else "2",
    )
    values["AI_IDS_ENV"] = "production" if env_choice == "2" else "development"

    values["AI_IDS_DEBUG"] = "true" if values["AI_IDS_ENV"] == "development" else "false"

    if values["AI_IDS_SECRET_KEY"] in (INSECURE_SECRET_KEY, ""):
        values["AI_IDS_SECRET_KEY"] = secrets.token_hex(32)
        print("  Secret key generated automatically.")
    else:
        if _confirm("  Generate a new secret key?", default=False):
            values["AI_IDS_SECRET_KEY"] = secrets.token_hex(32)
            print("  New secret key generated.")

    values["AI_IDS_BCRYPT_ROUNDS"] = _prompt("Bcrypt hash rounds", values["AI_IDS_BCRYPT_ROUNDS"])

    # ── Step 5: Telegram (optional) ───────────────────────────────────
    _subheading(f"Step 5/{_SETUP_STEPS}: Telegram Notifications (Optional)")
    if _confirm("  Enable Telegram threat notifications?", default=False):
        values["AI_IDS_TELEGRAM_BOT_TOKEN"] = _prompt(
            "Bot Token", values["AI_IDS_TELEGRAM_BOT_TOKEN"]
        )
        values["AI_IDS_TELEGRAM_CHAT_ID"] = _prompt(
            "Chat ID", values["AI_IDS_TELEGRAM_CHAT_ID"]
        )

        if values["AI_IDS_TELEGRAM_BOT_TOKEN"] and values["AI_IDS_TELEGRAM_CHAT_ID"]:
            if _confirm("  Test Telegram connection now?", default=True):
                _test_telegram(values["AI_IDS_TELEGRAM_BOT_TOKEN"], values["AI_IDS_TELEGRAM_CHAT_ID"])
    else:
        values["AI_IDS_TELEGRAM_BOT_TOKEN"] = ""
        values["AI_IDS_TELEGRAM_CHAT_ID"] = ""

    # ── Step 6: Network Capture ───────────────────────────────────────
    _subheading(f"Step 6/{_SETUP_STEPS}: Network Capture Settings")
    live_choice = _prompt(
        "Live capture engine (1=Native, 2=CICFlowMeter)",
        "1" if values["AI_IDS_LIVE_CAPTURE_MODE"] == "native" else "2",
    )
    values["AI_IDS_LIVE_CAPTURE_MODE"] = "cicflowmeter" if live_choice == "2" else "native"

    ext_choice = _prompt(
        "Offline flow extractor (1=Native, 2=CICFlowMeter)",
        "1" if values["AI_IDS_FLOW_EXTRACTOR"] == "native" else "2",
    )
    values["AI_IDS_FLOW_EXTRACTOR"] = "cicflowmeter" if ext_choice == "2" else "native"

    values["AI_IDS_FLOW_IDLE_TIMEOUT"] = _prompt(
        "Flow idle timeout (seconds)", values["AI_IDS_FLOW_IDLE_TIMEOUT"]
    )
    values["AI_IDS_MONITORING_INTERVAL"] = _prompt(
        "Monitoring poll interval (seconds)", values["AI_IDS_MONITORING_INTERVAL"]
    )
    values["AI_IDS_CICFLOWMETER_INTERVAL_SECONDS"] = _prompt(
        "CICFlowMeter flush interval (seconds)", values["AI_IDS_CICFLOWMETER_INTERVAL_SECONDS"]
    )
    values["AI_IDS_ALERT_WINDOW_MINUTES"] = _prompt(
        "Alert aggregation window (minutes)", values["AI_IDS_ALERT_WINDOW_MINUTES"]
    )

    # ── Step 7: Save ──────────────────────────────────────────────────
    _subheading(f"Step 7/{_SETUP_STEPS}: Save Configuration")
    _heading("Configuration Summary")
    print(f"  Environment   : {values['AI_IDS_ENV']}")
    print(f"  Database      : {values['AI_IDS_DB_PATH']}")
    print(f"  Models dir    : {values['AI_IDS_MODELS_DIR']}")
    print(f"  Logs dir      : {values['AI_IDS_LOGS_DIR']}")
    print(f"  Log level     : {values['AI_IDS_LOG_LEVEL']}")
    print(f"  Bcrypt rounds : {values['AI_IDS_BCRYPT_ROUNDS']}")
    print(f"  Flow extractor: {values['AI_IDS_FLOW_EXTRACTOR']}")
    tg_status = "configured" if values.get("AI_IDS_TELEGRAM_BOT_TOKEN") else "not configured"
    print(f"  Telegram      : {tg_status}")
    print()

    if not _confirm("  Save this configuration?", default=True):
        print("  Setup cancelled. No changes saved.")
        return False

    _write_env(values)
    print(f"\n  Configuration saved to: {_ENV_PATH}")
    print("  IMPORTANT: Restart the application for changes to take effect.\n")

    return True


def _test_telegram(token: str, chat_id: str) -> None:
    print("  Testing Telegram connection...")
    try:
        from infrastructure.notifications.telegram_notifier import TelegramNotifier
        notifier = TelegramNotifier(bot_token=token, chat_id=chat_id)
        ok = notifier.send_test_alert()
        if ok:
            print("  Telegram test message sent successfully!")
        else:
            print("  Telegram test failed. Check your Bot Token and Chat ID.")
    except Exception as exc:
        print(f"  Telegram test error: {exc}")


# ===========================================================================
# STREAMLIT LAUNCHER
# ===========================================================================

def cmd_launch_streamlit() -> None:
    """Launch the Streamlit web UI as a subprocess."""
    _heading("Launching AI-IDS Web Interface")
    app_path = _BASE_DIR / "app.py"
    if not app_path.exists():
        print("  ERROR: app.py not found in project root.")
        return

    print("  Starting Streamlit server...")
    print(f"  The browser will open automatically at {_STREAMLIT_URL}")
    print("  Press Ctrl+C in this terminal to stop the server.\n")

    try:
        process = subprocess.Popen(
            [sys.executable, "-m", "streamlit", "run", str(app_path),
             "--server.headless", "false",
             "--browser.gatherUsageStats", "false"],
            cwd=str(_BASE_DIR),
        )
        process.wait()
    except KeyboardInterrupt:
        print("\n  Streamlit server stopped.")
        process.terminate()


# ===========================================================================
# MAIN MENU
# ===========================================================================

_MENU_ITEMS: Final[dict[str, tuple[str, str]]] = {
    "1":  ("setup",               "Setup Wizard (Configure System)"),
    "2":  ("launch-ui",           "Launch Web Interface (Streamlit)"),
    "3":  ("status",              "System Status & Health"),
    "4":  ("list-models",         "List Registered Detection Models"),
    "5":  ("analyze-csv",         "Batch CSV Traffic Analysis"),
    "6":  ("analyze-pcap",        "PCAP File Traffic Analysis"),
    "7":  ("live-capture",        "Live Network Capture & Detection"),
    "8":  ("predict",             "Single-Vector Real-Time Inference"),
    "9":  ("alerts",              "Query Recent Security Alerts"),
    "10": ("logs",                "View Recent System Logs"),
    "11": ("whitelist",           "Whitelist IP Management"),
    "12": ("blacklist",           "Blacklist IP Management"),
    "13": ("test-telegram",       "Send Telegram Test Message"),
    "14": ("list-interfaces",     "List Network Interfaces"),
    "0":  ("exit",                "Exit"),
}


def _show_banner() -> None:
    os_name = _detect_os()
    py_ver = _detect_python()
    env_label = "configured" if _env_exists() else "NOT configured"
    print(f"\n{'AI-IDS — Intrusion Detection System':^62}")
    print(f"{f'v{_APP_VERSION}  |  {os_name}  |  Python {py_ver}':^62}")
    print(f"{f'Config: {env_label}':^62}")
    print(_DIV)


def _show_menu() -> None:
    print()
    for key, (_, desc) in _MENU_ITEMS.items():
        label = key.rjust(3)
        print(f"  [{label}]  {desc}")
    print()
    max_key = max(int(k) for k in _MENU_ITEMS.keys())
    choice = input(f"  Select [0-{max_key}]: ").strip()
    return choice


def _main_menu() -> None:
    from services.container import get_container

    while True:
        _show_banner()
        choice = _show_menu()

        if choice == "0":
            print("\n  Session terminated. Goodbye.\n")
            break

        handler = _MENU_ITEMS.get(choice, (None, None))[0]
        if handler is None:
            print("  Invalid selection.")
            continue

        # Handlers that don't need the container
        if handler == "setup":
            run_setup_wizard()
            continue
        if handler == "launch-ui":
            cmd_launch_streamlit()
            continue

        # All other handlers need the container
        try:
            container = get_container()
        except Exception as exc:
            print(f"\n  ERROR: Failed to initialize system: {exc}")
            print("  Try running the Setup Wizard first (option 1).\n")
            input("  Press Enter to continue...")
            continue

        if handler == "status":
            _menu_status(container)
        elif handler == "list-models":
            _menu_list_models(container)
        elif handler == "analyze-csv":
            _menu_csv(container)
        elif handler == "analyze-pcap":
            _menu_pcap(container)
        elif handler == "live-capture":
            _menu_live(container)
        elif handler == "predict":
            _menu_predict(container)
        elif handler == "alerts":
            _menu_alerts(container)
        elif handler == "logs":
            _menu_logs(container)
        elif handler == "whitelist":
            _menu_whitelist(container)
        elif handler == "blacklist":
            _menu_blacklist(container)
        elif handler == "test-telegram":
            _menu_test_telegram(container)
        elif handler == "list-interfaces":
            _menu_interfaces()

        input("\n  Press Enter to continue...")


# ── Individual menu handlers ──────────────────────────────────────────

def _menu_status(container: Container) -> None:
    from config.settings import get_settings
    from capture.live_capture_service import get_live_capture_service

    settings = get_settings()
    models = container.model_repository.get_all()
    active_models = [m for m in models if m.is_active]
    alerts = container.alert_repository.get_recent(limit=100)
    active_alerts = [a for a in alerts if not a.is_acknowledged]
    live_service = get_live_capture_service()
    cap = live_service.status

    _heading("System Status")
    print(f"  Version        : {_APP_VERSION}")
    print(f"  Environment    : {settings.app_env}")
    print(f"  Python         : {platform.python_version()}")
    print(f"  Platform       : {platform.system()} {platform.release()}")
    print(f"  Database       : {settings.database_path}")
    print(f"  Models Dir     : {settings.models_dir}")
    print(f"  Log Level      : {settings.log_level}")
    print(_SUB)
    print(f"  Models total   : {len(models)} ({len(active_models)} active)")
    print(f"  Alerts active  : {len(active_alerts)}")
    print(f"  Capture active : {cap.get('is_running', False)}")
    if cap.get("is_running"):
        print(f"  Capture pkts   : {cap.get('packet_count', 0)}")
        print(f"  Capture flows  : {cap.get('active_flows', 0)}")
    tg = "configured" if settings.telegram_bot_token else "not configured"
    print(f"  Telegram       : {tg}")
    print(_DIV)


def _menu_list_models(container: Container) -> None:
    _heading("Registered ML Models")
    models = container.model_repository.get_all()
    if not models:
        print("  No models registered.")
        return
    print(f"  {'ID':<6} | {'Name':<26} | {'Type':<14} | {'Active'}")
    print(f"  {_SUB}")
    for m in models:
        flag = "Yes" if m.is_active else "No"
        print(f"  {m.id:<6} | {m.name:<26} | {m.model_type:<14} | {flag}")
    print(f"  {_SUB}\n")


def _menu_csv(container: Container) -> None:
    _heading("Batch CSV Traffic Analysis")
    mid = _prompt("Model ID")
    fpath = _prompt("CSV file path")
    rows = _prompt("Max rows (Enter = unlimited)", "")

    if not mid.isdigit():
        print("  ERROR: Model ID must be a number.")
        return
    model_id = int(mid)

    path = Path(fpath.strip().strip("\"'"))
    if not path.exists():
        print(f"  ERROR: File not found: {path}")
        return

    print(f"\n  Analyzing {path.name} with model {model_id}...")
    try:
        summary = container.csv_analysis_service.analyze(
            model_id=model_id,
            csv_path=str(path),
            max_rows=int(rows) if rows.isdigit() else None,
        )
    except Exception as exc:
        print(f"  ERROR: {exc}")
        return

    ratio = (summary.attack_count / summary.total_rows * 100) if summary.total_rows else 0.0
    print(_DIV)
    print(f"  Total Rows Evaluated : {summary.total_rows}")
    print(f"  Normal Traffic       : {summary.normal_count}")
    print(f"  Malicious Anomalies  : {summary.attack_count}")
    print(f"  Threat Density       : {ratio:.2f}%")
    print(_DIV)


def _menu_pcap(container: Container) -> None:
    _heading("PCAP File Traffic Analysis")
    mid = _prompt("Model ID")
    fpath = _prompt("PCAP file path")

    if not mid.isdigit():
        print("  ERROR: Model ID must be a number.")
        return
    model_id = int(mid)

    path = Path(fpath.strip().strip("\"'"))
    if not path.exists():
        print(f"  ERROR: File not found: {path}")
        return

    print(f"\n  Analyzing {path.name} with model {model_id}...")
    try:
        summary = container.pcap_analysis_service.analyze(
            model_id=model_id,
            pcap_path=str(path),
        )
    except Exception as exc:
        print(f"  ERROR: {exc}")
        return

    print(_DIV)
    print(f"  Evaluated Flows  : {summary.total_flows}")
    print(f"  Detected Threats : {summary.attack_count}")
    print(f"  Normal Flows     : {summary.normal_count}")
    print(_DIV)


def _menu_live(container: Container) -> None:
    from capture.interface_lister import NetworkInterfaceLister
    from capture.live_capture_service import get_live_capture_service

    _heading("Live Network Capture & Detection")
    mid = _prompt("Model ID")
    if not mid.isdigit():
        print("  ERROR: Model ID must be a number.")
        return
    model_id = int(mid)

    try:
        _, model_name = _resolve_model_id(container, model_id)
    except ValueError as exc:
        print(f"  ERROR: {exc}")
        return

    try:
        ifaces = NetworkInterfaceLister().list_interfaces()
    except Exception:
        ifaces = []

    interface: str | None = None
    if ifaces:
        print("\n  Available interfaces:")
        for idx, iface in enumerate(ifaces, 1):
            status = "UP" if iface.is_up else "DOWN"
            print(f"    [{idx}] {iface.display_name} ({status})")
        print("    [0] Auto-detect")
        sel = input(f"\n  Select [0-{len(ifaces)}]: ").strip()
        if sel.isdigit() and 1 <= int(sel) <= len(ifaces):
            interface = ifaces[int(sel) - 1].system_name
    else:
        raw = _prompt("Interface name (Enter = auto-detect)", "")
        interface = raw or None

    live_service = get_live_capture_service()
    print(f"\n  Starting live capture with model: {model_name}")
    try:
        live_service.start(
            interface=interface or "",
            model_id=model_id,
            model_name=model_name,
        )
    except Exception as exc:
        print(f"  ERROR: {exc}")
        return

    print("  Live capture running. Press Ctrl+C to stop.\n")
    try:
        while live_service.status.get("is_running", False):
            st = live_service.status
            print(
                f"\r  Packets: {st.get('packet_count', 0):>8}  "
                f"Flows: {st.get('active_flows', 0):>6}",
                end="", flush=True,
            )
            time.sleep(1.0)
    except KeyboardInterrupt:
        print("\n\n  Capture stopped.")
    return


def _menu_predict(container: Container) -> None:
    _heading("Single-Vector Real-Time Inference")
    mid = _prompt("Model ID")
    if not mid.isdigit():
        print("  ERROR: Model ID must be a number.")
        return
    model_id = int(mid)

    try:
        _, model_name = _resolve_model_id(container, model_id)
    except ValueError as exc:
        print(f"  ERROR: {exc}")
        return

    fjson = _prompt("Feature JSON string")
    src_ip = _prompt("Source IP", _DEFAULT_SOURCE_IP)
    dst_ip = _prompt("Destination IP", _DEFAULT_DEST_IP)

    try:
        raw_features = json.loads(fjson)
    except json.JSONDecodeError as exc:
        print(f"  ERROR: Invalid JSON: {exc}")
        return

    print(f"\n  Running inference with model: {model_name}...")
    try:
        result = container.detection_service.run(
            model_id=model_id,
            raw_features=raw_features,
            source_type="cli",
            source_ip=src_ip,
            destination_ip=dst_ip,
        )
    except Exception as exc:
        print(f"  ERROR: {exc}")
        return

    from services.detection_service import BENIGN_CLASS_INDEX
    verdict = "THREAT DETECTED" if result.prediction != BENIGN_CLASS_INDEX else "BENIGN TRAFFIC"
    print(_DIV)
    print(f"  Verdict          : {verdict}")
    print(f"  Confidence       : {result.confidence:.4f}")
    print(f"  Attack Type      : {result.attack_type}")
    print(f"  Model            : {model_name} (ID {model_id})")
    print(_DIV)


def _menu_alerts(container: Container) -> None:
    _heading("Recent Security Alerts")
    limit_str = _prompt("Max alerts to display", str(_DEFAULT_ALERT_LIMIT))
    limit = int(limit_str) if limit_str.isdigit() else _DEFAULT_ALERT_LIMIT

    alerts = container.alert_repository.get_recent(limit=limit)
    if not alerts:
        print("  No active alerts.")
        return

    print(f"  {'ID':<6} | {'Created At':<20} | {'Source IP':<16} | {'Threat Type'}")
    print(f"  {_SUB}")
    for a in alerts:
        ts = str(a.first_seen)[:19]
        print(f"  {a.id or '-':<6} | {ts:<20} | {a.source_ip:<16} | {a.threat_type}")
    print(f"  {_SUB}\n")


def _menu_logs(container: Container) -> None:
    _heading("Recent System Logs")
    limit_str = _prompt("Max logs to display", str(_DEFAULT_LOG_LIMIT))
    limit = int(limit_str) if limit_str.isdigit() else _DEFAULT_LOG_LIMIT

    logs = container.log_repository.search(limit=limit)
    if not logs:
        print("  No logs found.")
        return

    print(f"  {'ID':<5} | {'Level':<8} | {'Source':<10} | {'Message'}")
    print(f"  {_SUB}")
    for log in logs:
        msg = log.message[:50] + "..." if len(log.message) > 50 else log.message
        print(f"  {log.id or '-':<5} | {str(log.level.value):<8} | {str(log.source.value):<10} | {msg}")
    print(f"  {_SUB}\n")


def _menu_whitelist(container: Container) -> None:
    _heading("Whitelist IP Management")
    print("  [1] Add IP to Whitelist")
    print("  [2] Remove IP from Whitelist")
    print("  [3] View Whitelist")
    print("  [0] Back")
    choice = input("\n  Select: ").strip()

    if choice == "1":
        ip = _prompt("IP Address")
        reason = _prompt("Reason", "")
        container.ip_list_service.add_to_whitelist(ip, reason)
        print(f"  {ip} added to whitelist.")
    elif choice == "2":
        ip = _prompt("IP Address to remove")
        entries = container.ip_list_service.search_whitelist(ip)
        if not entries:
            print(f"  No whitelist entry found for {ip}.")
        else:
            container.ip_list_service.remove_from_whitelist(entries[0].id)
            print(f"  {ip} removed from whitelist.")
    elif choice == "3":
        entries = container.ip_list_service.list_whitelist()
        if not entries:
            print("  Whitelist is empty.")
        else:
            print(f"  {'ID':<5} | {'IP Address':<16} | {'Reason'}")
            print(f"  {_SUB}")
            for e in entries:
                print(f"  {e.id:<5} | {e.ip_address:<16} | {e.reason}")


def _menu_blacklist(container: Container) -> None:
    _heading("Blacklist IP Management")
    print("  [1] Add IP to Blacklist")
    print("  [2] Remove IP from Blacklist")
    print("  [3] View Blacklist")
    print("  [0] Back")
    choice = input("\n  Select: ").strip()

    if choice == "1":
        ip = _prompt("IP Address")
        reason = _prompt("Reason", "")
        container.ip_list_service.add_to_blacklist(ip, reason)
        print(f"  {ip} added to blacklist.")
    elif choice == "2":
        ip = _prompt("IP Address to remove")
        entries = container.ip_list_service.search_blacklist(ip)
        if not entries:
            print(f"  No blacklist entry found for {ip}.")
        else:
            container.ip_list_service.remove_from_blacklist(entries[0].id)
            print(f"  {ip} removed from blacklist.")
    elif choice == "3":
        entries = container.ip_list_service.list_blacklist()
        if not entries:
            print("  Blacklist is empty.")
        else:
            print(f"  {'ID':<5} | {'IP Address':<16} | {'Reason'}")
            print(f"  {_SUB}")
            for e in entries:
                print(f"  {e.id:<5} | {e.ip_address:<16} | {e.reason}")


def _menu_test_telegram(container: Container) -> None:
    _heading("Telegram Connection Test")
    settings = container.telegram_notifier
    if not settings.is_configured:
        print("  Telegram is not configured.")
        print("  Run the Setup Wizard (option 1) to configure Telegram.")
        return

    print("  Sending test message...")
    try:
        ok = settings.send_test_alert()
        if ok:
            print("  Test message sent successfully! Check your Telegram.")
        else:
            print("  Failed to send test message.")
    except Exception as exc:
        print(f"  Error: {exc}")


def _menu_interfaces() -> None:
    from capture.interface_lister import NetworkInterfaceLister

    _heading("Network Interfaces")
    try:
        ifaces = NetworkInterfaceLister().list_interfaces()
    except Exception as exc:
        print(f"  ERROR: {exc}")
        return

    if not ifaces:
        print("  No active network interfaces detected.")
        return

    for idx, iface in enumerate(ifaces, 1):
        status = "UP" if iface.is_up else "DOWN"
        print(f"  [{idx}] {iface.display_name:<40} ({status})")
    print()


# ===========================================================================
# Shared helper for model resolution
# ===========================================================================

def _resolve_model_id(container: Container, model_id: int) -> tuple[int, str]:
    record = container.model_repository.get_by_id(model_id)
    if record is None:
        raise ValueError(f"Model ID {model_id} does not exist.")
    return record.id, record.name


# ===========================================================================
# Argparse CLI (scripted / CI mode — preserved for backward compat)
# ===========================================================================

def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="ai-ids",
        description="AI-IDS — AI-Driven Intrusion Detection System CLI",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Interactive mode:\n"
            "  python cli.py                  Launch the interactive menu\n"
            "  python cli.py setup            Run the setup wizard\n"
            "  python cli.py launch           Start the web interface\n"
            "\nScripted mode:\n"
            "  python cli.py status\n"
            "  python cli.py list-models\n"
            "  python cli.py analyze-csv -m 1 -f data/traffic.csv\n"
            "  python cli.py predict -m 1 -d '{\"flow_duration\": 0.05}'\n"
        ),
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {_APP_VERSION}")

    sub = parser.add_subparsers(dest="command", help="Available commands")

    sub.add_parser("setup", help="Run the interactive setup wizard.")
    sub.add_parser("launch", help="Launch the Streamlit web interface.")
    sub.add_parser("status", help="Display system health summary.")
    sub.add_parser("list-models", help="List all registered ML models.")
    sub.add_parser("list-interfaces", help="List network interfaces.")

    p_csv = sub.add_parser("analyze-csv", help="Batch CSV traffic analysis.")
    p_csv.add_argument("-m", "--model-id", type=int, required=True)
    p_csv.add_argument("-f", "--file", required=True)
    p_csv.add_argument("-r", "--max-rows", type=int, default=None)

    p_pcap = sub.add_parser("analyze-pcap", help="PCAP file traffic analysis.")
    p_pcap.add_argument("-m", "--model-id", type=int, required=True)
    p_pcap.add_argument("-f", "--file", required=True)

    p_live = sub.add_parser("live-capture", help="Live network capture and detection.")
    p_live.add_argument("-m", "--model-id", type=int, required=True)
    p_live.add_argument("-i", "--interface", default=None)
    p_live.add_argument("-p", "--packets", type=int, default=100)

    p_pred = sub.add_parser("predict", help="Single-vector real-time inference.")
    p_pred.add_argument("-m", "--model-id", type=int, required=True)
    p_pred.add_argument("-d", "--data", required=True)
    p_pred.add_argument("--src-ip", default=_DEFAULT_SOURCE_IP)
    p_pred.add_argument("--dst-ip", default=_DEFAULT_DEST_IP)

    p_alerts = sub.add_parser("alerts", help="Query recent security alerts.")
    p_alerts.add_argument("-n", "--limit", type=int, default=_DEFAULT_ALERT_LIMIT)

    return parser


def main() -> None:
    """Main entry point."""
    _ensure_utf8()

    parser = _build_parser()
    args = parser.parse_args()

    # No command → launch interactive menu (auto-detect first run)
    if not args.command:
        if not _env_exists():
            _heading("Welcome to AI-IDS")
            print("  No configuration file detected.")
            print("  Let's set up your system.\n")
            if _confirm("  Start Setup Wizard now?", default=True):
                if run_setup_wizard():
                    print("  Setup complete! Launching operations console...\n")
                else:
                    print("  Setup was not completed. You can run it later with: python cli.py setup\n")
        _main_menu()
        sys.exit(0)

    # Scripted commands
    cmd = args.command
    if cmd == "setup":
        run_setup_wizard()
    elif cmd == "launch":
        cmd_launch_streamlit()
    else:
        from services.container import get_container
        try:
            container = get_container()
        except Exception as exc:
            print(f"Error: Failed to initialize system: {exc}", file=sys.stderr)
            sys.exit(1)

        dispatch = {
            "status":           lambda: _menu_status(container),
            "list-models":      lambda: _menu_list_models(container),
            "list-interfaces":  lambda: _menu_interfaces(),
            "analyze-csv":      lambda: cmd_analyze_csv_scripted(container, args.model_id, args.file, args.max_rows),
            "analyze-pcap":     lambda: cmd_analyze_pcap_scripted(container, args.model_id, args.file),
            "live-capture":     lambda: cmd_live_capture_scripted(container, args.model_id, args.interface, args.packets),
            "predict":          lambda: cmd_predict_scripted(container, args.model_id, args.data, args.src_ip, args.dst_ip),
            "alerts":           lambda: cmd_alerts_scripted(container, args.limit),
        }
        handler = dispatch.get(cmd)
        if handler:
            try:
                exit_code = handler()
            except (ValueError, RuntimeError) as exc:
                print(f"Error: {exc}", file=sys.stderr)
                sys.exit(1)
            sys.exit(exit_code or 0)
        parser.print_help()


# ── Scripted command helpers (for argparse mode) ──────────────────────

def cmd_analyze_csv_scripted(container, model_id, file_path, max_rows):
    path = Path(file_path.strip().strip("\"'"))
    if not path.exists():
        print(f"Error: File not found: {path}", file=sys.stderr)
        return 1
    _resolve_model_id(container, model_id)
    summary = container.csv_analysis_service.analyze(model_id=model_id, csv_path=str(path), max_rows=max_rows)
    ratio = (summary.attack_count / summary.total_rows * 100) if summary.total_rows else 0.0
    print(f"Total: {summary.total_rows} | Normal: {summary.normal_count} | Attacks: {summary.attack_count} | Threat: {ratio:.2f}%")
    return 0


def cmd_analyze_pcap_scripted(container, model_id, file_path):
    path = Path(file_path.strip().strip("\"'"))
    if not path.exists():
        print(f"Error: File not found: {path}", file=sys.stderr)
        return 1
    _resolve_model_id(container, model_id)
    summary = container.pcap_analysis_service.analyze(model_id=model_id, pcap_path=str(path))
    print(f"Flows: {summary.total_flows} | Threats: {summary.attack_count} | Normal: {summary.normal_count}")
    return 0


def cmd_live_capture_scripted(container, model_id, interface, packets):
    from capture.live_capture_service import get_live_capture_service
    _, model_name = _resolve_model_id(container, model_id)
    live = get_live_capture_service()
    live.start(interface=interface or "", model_id=model_id, model_name=model_name)
    print(f"Live capture running (max {packets} packets). Ctrl+C to stop.")
    try:
        count = 0
        while live.status.get("is_running", False):
            st = live.status
            count = st.get("packet_count", 0)
            print(f"\r  Packets: {count:>8}  Flows: {st.get('active_flows', 0):>6}", end="", flush=True)
            time.sleep(1.0)
            if count >= packets:
                break
    except KeyboardInterrupt:
        pass
    print("\nCapture stopped.")
    return 0


def cmd_predict_scripted(container, model_id, features_json, src_ip, dst_ip):
    from services.detection_service import BENIGN_CLASS_INDEX
    _, model_name = _resolve_model_id(container, model_id)
    raw_features = json.loads(features_json)
    result = container.detection_service.run(model_id=model_id, raw_features=raw_features, source_type="cli", source_ip=src_ip, destination_ip=dst_ip)
    verdict = "THREAT" if result.prediction != BENIGN_CLASS_INDEX else "BENIGN"
    print(f"Verdict: {verdict} | Confidence: {result.confidence:.4f} | Model: {model_name}")
    return 0


def cmd_alerts_scripted(container, limit):
    alerts = container.alert_repository.get_recent(limit=limit)
    if not alerts:
        print("No alerts.")
        return 0
    for a in alerts:
        ts = str(a.first_seen)[:19]
        print(f"  [{a.id}] {ts} | {a.source_ip} | {a.threat_type}")
    return 0


if __name__ == "__main__":
    main()
